### ISSUE TITLE
Custom license rationale and meaning?

### ISSUE THREAD

**Issue by JoshuaC215** [NirDiamant/Prompt_Engineering#1]
I noticed you’re using a custom license for this repo (which might not be immediately obvious to contributors!)

It seems like an unusual practice for this kind of repo as far as I’m aware. Wondered if you could explain the rationale for the decision and summarize the implications of this license? For example, if I wanted to reference this content internally while developing a commercial LLM application. Thanks!

**Comment by NirDiamant** [comment]
Answered you on LinkedIn :)
